### ISSUE TITLE
Would be nice if you would complete the credits

### ISSUE THREAD

**Issue by malle-pietje** [montreux-oberland-bernois/unifi-php-api#1]
Hi. Nice work, I'll also be setting up a dedicated repo for the UniFi API client class which I maintain.

One kind request: I would appreciate if you would add me and my repo to the credits for the code you pulled from my repo. In the past year or so I have invested quite a lot of time in it over the past year.

Thanks in advance!

**Comment by rafi16d** [comment]
Hi. Of course, I've completely forgotten that. I'm sorry. 
Thank you for your work

**Comment by malle-pietje** [comment]
Thanks! And you're welcome;-)
